ajouter:
    path:      /ajouter/{id}
    defaults:  { _controller: ECEcommerceBundle:Panier:ajouter }

panier:
    path:      /
    defaults:  { _controller: ECEcommerceBundle:Panier:panier }

supprimer:
    path:       /supprimer/{id}
    defaults:   { _controller: ECEcommerceBundle:Panier:supprimer }

livraison:
    path:       /livraison
    defaults:   { _controller: ECEcommerceBundle:Panier:livraison }