produits:
    path:     /
    defaults: { _controller: ECEcommerceBundle:Produits:produits }

presentation:
    path:     /produit/{id}
    defaults: { _controller: ECEcommerceBundle:Produits:presentation }

categorieProduits:
     path:     /categorie/{categorie}
     defaults: { _controller: ECEcommerceBundle:Produits:produits}